return {
  {
    'nvim-treesitter/nvim-treesitter-context',
    opts = {},
  },
  {
    'nvim-treesitter/nvim-treesitter',
    build = ':TSUpdate',
    main = 'nvim-treesitter.configs',
    opts = {
      ensure_installed = {
        'bash',
        'c',
        'cpp',
        'diff',
        'html',
        'lua',
        'luadoc',
        'markdown',
        'markdown_inline',
        'query',
        'vim',
        'vimdoc',
        'vue',
        'c_sharp',
        'typescript',
        'javascript',
        'css',
        'rust',
        'csv',
        'dockerfile',
        'editorconfig',
        'dot',
        'gitignore',
        'glsl',
        'hlsl',
        'ini',
        'json5',
        'latex',
        'llvm',
        'make',
        'meson',
        'nasm',
        'nginx',
        'objc',
        'odin',
        'proto',
        'properties',
        'python',
        'scss',
        'sql',
        'terraform',
        'toml',
        'wgsl',
        'xml',
        'yaml',
        'vim',
        'vimdoc',
        'zig',
      },
      auto_install = true,
      highlight = {
        enable = true,
        additional_vim_regex_highlighting = { 'ruby' },
      },
      indent = { enable = true, disbale = { 'ruby' } },
    },
  },
}
